source 'https://rubygems.org'


gem 'rails', '4.2.10'

gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'carrierwave'
gem 'coffee-rails'
gem 'devise'
gem 'devise-i18n'
gem 'devise-i18n-views'
gem 'font-awesome-rails'
gem 'therubyracer'
gem 'jquery-rails'
gem 'mini_magick'
gem 'premailer-rails'
gem 'sass-rails', '~> 5.0'
gem 'sqlite3'
gem 'squasher'
gem 'turbolinks'


group :development do
  gem 'annotate'
  gem 'hirb'
  gem 'hirb-unicode'
  gem 'letter_opener_web'
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'pry-stack_explorer'
  # gem 'rubocop', require: false
  gem 'spring'
  gem 'view_source_map'
  gem 'web-console', '~> 2.0'
end


group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end


group :production do
  gem 'rails_12factor'
end
